# permissions for end users to edit hellos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hello-editor-role
rules:
- apiGroups:
  - cache.hello.example.com
  resources:
  - hellos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.hello.example.com
  resources:
  - hellos/status
  verbs:
  - get
